# Generated by Django 4.0.3 on 2022-03-10 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='ponentes/images')),
                ('nombre_apellido', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('universidad', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=200)),
                ('ciudad', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MiniCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion_curso', models.TextField()),
                ('dia', models.DateField()),
                ('hora', models.TimeField()),
                ('ponente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='congreso.ponente')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion_curso', models.TextField()),
                ('dia', models.DateField()),
                ('hora', models.TimeField()),
                ('ponente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='congreso.ponente')),
            ],
        ),
    ]
