# Generated by Django 4.0.2 on 2022-02-28 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('universidad', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to='ponentes/images')),
                ('curso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='congreso.curso')),
            ],
        ),
    ]
